# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Test Suite for dcicsnovault

    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # run postgres in a Docker container
    services:
      postgres:
        image: postgres:11

        ports:
          - 5432:5440

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install Deps
        run: |
          make build

      - name: QA
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_ENCRYPT_KEY: ${{ secrets.S3_ENCRYPT_KEY }}
          TRAVIS_JOB_ID: temporary_test_prefix # XXX: replace me
        run: |
          make travis-test


      - name: Cleanup
        if: ${{ always() }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_ENCRYPT_KEY: ${{ secrets.S3_ENCRYPT_KEY }}
          TRAVIS_JOB_ID: temporary_test_prefix # XXX: replace me
        run: |
          poetry run wipe-test-indices $TRAVIS_JOB_ID search-fourfront-testing-6-8-kncqa2za2r43563rkcmsvgn2fq.us-east-1.es.amazonaws.com:443

